# Dockerfile.melodic
#
# To run Champ packages

FROM ros:melodic-ros-base

# Create ros_custom-melodic workspace

RUN mkdir -p /workspaces/ros_custom-humble/src

WORKDIR /workspaces/ros_custom-humble/src
RUN git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common.git
RUN git clone https://github.com/IntelRealSense/realsense-ros.git -b 4.51.1
RUN git clone --recurse-submodules https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox.git

WORKDIR /workspaces/ros_custom-humble/src/isaac_ros_nvblox
RUN git lfs pull

WORKDIR /workspaces/ros_custom-humble/src/isaac_ros_nvblox/nvblox_examples/realsense_splitter
RUN git update-index --assume-unchanged COLCON_IGNORE
RUN rm COLCON_IGNORE

WORKDIR /workspaces/ros_custom-humble

RUN apt-get update

RUN rosdep update
RUN rosdep install -i -r --from-paths src --rosdistro humble -y --skip-keys "libopencv-dev libopencv-contrib-dev libopencv-imgproc-dev python-opencv python3-opencv nvblox"

RUN apt-get install -y \
    ros-humble-isaac-ros-stereo-image-proc \
    ros-humble-isaac-ros-visual-slam

# Change workspaces owership

RUN chown -R admin:admin /workspaces
