services:
  ros-melodic:
    image: ros-melodic:test-openssh
    # build: 
    # context: ./ros_melodic
    volumes:
      - type: volume
        source: tmp
        target: /dev/shm
      - type: volume
        source: champ
        target: /champ
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      # - "/dev/ttyUSB1:/dev/ttyUSB1"
    ports:
      - 22:22
      - 6080:80
      - 5900:5900
    environment:
      - RESOLUTION=2140x1444
volumes:
  tmp:
  champ:
