services:
  ros-melodic:
    image: ros-melodic:test-openssh
    # build: 
    # context: ./ros_melodic
    volumes:
      - type: volume
        source: tmp
        target: /dev/shm
      - type: volume
        source: champ
        target: /champ
    devices:
        - "/dev/input/js0:/dev/input/js0"
        - "/dev/rfcomm1:/dev/ttyUSB0"
      # - "/dev/ttyUSB0:/dev/ttyUSB0"
      # - "/dev/ttyUSB1:/dev/ttyUSB1"
    ports:
      - 22:22
      - 6080:80
      - 5900:5900
      - 11411:11411 # ros serial port
      - 11311:11311
    environment:
      - RESOLUTION=2140x1444
volumes:
  tmp:
  champ:
