# Dockerfile.newviz
#
# To run web application

# Build the web application

FROM node:20.12.2 as build

WORKDIR /app

COPY --from=src package.json .

RUN npm install

COPY --from=src . .

RUN npm run build

# Create the nginx image

FROM nginx:stable

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

